#!/bin/bash

# Collect OS-Information
os_info=$(cat $4/etc/os-release | jq -R 'split("=") | {(.[0]): (.[1] | gsub("\""; ""))}' | jq -s 'add')

# Collect Package-Information
packages=$(chroot $4 dpkg-query -l | awk '$1 == "ii" {print $2, $3}' | jq -R 'split(" ") | {name: .[0], version: .[1]}' | jq -s .)

# Add node to package list and sort
packages=$(echo "$packages" | jq --arg version "$7" '. + [{name: "node", version: $version}] | sort_by(.name)')

# Construct json
jq -n \
  --argjson os_info "$os_info" \
  --argjson packages "$packages" \
  --arg channel "$1" \
  --arg version "$2" \
  --arg recommended_kernel "$3" \
  --arg frontend "$5" \
  --arg api "$6" \
  '{
    mos: {
      version: $version,
      build: (now | strftime("%Y%m%d-%H%M")),
      recommended_kernel: $recommended_kernel,
      channel: $channel,
      frontend: $frontend,
      api: $api
    },
    base: [{
      os_name: $os_info.NAME,
      os_version: $os_info.VERSION,
      os_id: $os_info.ID,
      os_version_id: $os_info.VERSION_ID,
      packages: $packages
    }]
  }'
