#!/bin/sh
# MOS custom

### BEGIN INIT INFO
# Provides:          installplugins-mos
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     S
# Default-Stop:
# Short-Description: Install MOS Plugins
# Description:       Run MOS Plugin installation
### END INIT INFO

PATH="/sbin:/bin:/usr/sbin:/usr/bin"
DESC="MOS Plugins"
NAME="installplugins-mos"
RUN_DIR="/run"

. /lib/lsb/init-functions

install_plugins() {
  # Get all plugin directories
  for plugin in /boot/optional/plugins/*; do
    # Set installation done and get version paths
    INSTALLATION_DONE=false
    VERSION_PATH=$(ls -d $plugin/*/ 2>/dev/null | sort -V | tail -1)
    if [ ! -z "$VERSION_PATH" ] ; then
      PACKAGE_PATH=$(ls "$VERSION_PATH"*.deb 2>/dev/null)
      # If there is not .deb package in Version folder it's proabably not a plugin
      if [ ! -z "$PACKAGE_PATH" ] ; then
        DISPLAY_NAME=$(jq -r '.name' $plugin/template.json)
        logger -t "MOS Plugins: $DISPLAY_NAME" "Installing: ${PACKAGE_PATH##*/}" 
        DEBIAN_FRONTEND=noninteractive dpkg -i $PACKAGE_PATH >/dev/null 2>&1
        INSTALLATION_DONE=true
      fi
      # Run functions file if found (in subshell to avoid using variables from function in mos_start)
      if [ -f "$VERSION_PATH/functions" ] ; then
        (
          source $VERSION_PATH/functions
          if type mos_start &>/dev/null ; then
            logger -t "MOS Plugins: $DISPLAY_NAME" "Executing start script"
            mos_start 2>&1 | logger -t "MOS Plugins: $DISPLAY_NAME"
            EXIT_STATUS=${PIPESTATUS[0]}
            if [ "$EXIT_STATUS" != "0" ] ; then
              logger -t "MOS Plugins: $DISPLAY_NAME" "ERROR: Running start script"
              exit 1
            else
              logger -t "MOS Plugins: $DISPLAY_NAME" "Start script finished successful"
              exit 0
            fi
          fi
        )
        INSTALLATION_DONE=true
      fi
    fi
    if [ "$INSTALLATION_DONE" == "true" ] ; then
      logger -t "MOS Plugins: $DISPLAY_NAME" "Installation finished"
    fi
    unset INSTALLATION_DONE VERSION_PATH PACKAGE_PATH DISPLAY_NAME
  done
}

case "$1" in
  start)
    log_daemon_msg "Installing $DESC" "$NAME"
    install_plugins
    log_end_msg 0
  ;;
  stop)
    exit 0
  ;;
esac
